### ISSUE TITLE
Create a basic CLI bank interface

### ISSUE THREAD

**Issue by koden-km** [dogmatiq/example#23]
Something that can be used to interact with the system and perform the example banking actions. A simple runtime loop with menu options would be enough.

* Login (doesn't actually need to have passwords)
* Deposit
* Withdraw
* Transfer (with optional future scheduled date)
* Report

**Comment by koden-km** [comment]
As suggested by @jmalloc, the server doesn't need to be running all the time. On startup it will just catchup time and handle any pending messages.

**Comment by jmalloc** [comment]
> the server doesn't need to be running all the time

This would be true for an engine with persistence, but the most functional engine implementation that has persistence is Ax which is way too much to include here (it needs RMQ, mysql, etc).

That said, I wasn't originally considering an *interactive* app (runtime loop, with menu options, etc) ... if you made it interactive you could just use the in-memory engine from testkit just fine!

**Comment by jmalloc** [comment]
I've updated the title of this issue to reflect our intent to build something interactive (so that we can use the in-memory engine, etc).

**Comment by koden-km** [comment]
Steps:
- [ ] Convert the CSV read-model to use projectionkit/sqlite #20
- [ ] Create a customer projection for the select customer UI #29
- [ ] Create a ledger projection for the view ledger UI #32
- [ ] Create a pending transfer projection for the list scheduled transfers UI #31
